# Generated by Django 5.0.7 on 2024-08-06 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homesection",
            name="description",
        ),
    ]
