# Generated by Django 5.0.7 on 2024-08-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_picture", models.ImageField(upload_to="about_pics/")),
                ("experience_icon", models.ImageField(upload_to="icons/")),
                ("education_icon", models.ImageField(upload_to="icons/")),
                ("experience_text", models.CharField(max_length=255)),
                ("education_text", models.CharField(max_length=255)),
                ("about_text", models.TextField()),
            ],
        ),
    ]
