# Generated by Django 5.0.7 on 2024-08-06 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutsection",
            name="education_icon",
        ),
        migrations.RemoveField(
            model_name="aboutsection",
            name="experience_icon",
        ),
    ]
